paths:
  static: public
  uploads: public/images

collections_config:
  data:
    path: 'src/config'
    name: Site Config
    icon: analytics
  pages:
    path: 'src/content/pages/english'
    name: Pages
    url: '/en/[slug]/'
    _enabled_editors:
      - visual
    icon: wysiwyg
  pages_fr:
    path: 'src/content/pages/french'
    name: Pages
    url: '/fr/[slug]/'
    _enabled_editors:
      - visual
    icon: wysiwyg
  authors:
    path: src/content/authors/english
    url: '/en/authors/[slug]/'
    name: Authors
    icon: account_circle
  authors_fr:
    path: src/content/authors/french
    url: '/fr/authors/[slug]/'
    name: Authors (Fr)
    icon: account_circle
  blog:
    path: src/content/blog/english
    url: '/en/blog/[slug]/'
    name: Blog
    icon: newspaper
  blog_fr:
    path: src/content/blog/french
    url: '/fr/blog/[slug]/'
    name: Blog (Fr)
    icon: newspaper
  sections:
    path: src/content/sections/english
    name: Sections
    _enabled_editors:
      - data
    icon: analytics
  sections_fr:
    path: src/content/sections/french
    name: Sections (Fr)
    _enabled_editors:
      - data
    icon: analytics
  translations:
    path: src/i18n
    name: Src I18n
    _enabled_editors:
      - data
    icon: translate

collection_groups:
  - heading: English
    collections:
      - pages
      - authors
      - blog
  - heading: French
    collections:
      - pages_fr
      - authors_fr
      - blog_fr
  - heading: Data Files
    collections:
      - data
      - translations
      - sections
      - section_fr


timezone: Pacific/Auckland

markdown:
  engine: commonmark
  options:
    gfm: true
    linkify: false
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    breaks: false
    xhtml: false
    attributes: false
    typographer: false
    treat_indentation_as_code: true
_snippets_imports:
  hugo:
    exclude:
      - hugo_instagram
